malwarefrank/dnfile

src/dnfile/base.py
@malwarefrank just a quick fix to prevent coded indexes from always being `None`. Thank you for the great tool!
=> fix coded indexes always None bug

src/dnfile/base.py
`ClrMetaDataTable.rows` is zero-based so we need to subtract one from the RID when setting `MDTableIndex.row`.
=> fix MDTableIndex RID off-by-one bug

src/dnfile/base.py
ClrMetaDataTable.row_index is one-indexed so the range check should not decrement the `num_rows` limit.
=> CodedIndex: fix off-by-one during row bounds check

.github/workflows/lint.yml
Adds a skeleton configuration for CI via Github Actions. Right now, it just demonstrates that the package can be installed. I'd recommend other steps, just a style, type checking, formatting, and testing, but I'll propose those in separate PRs so you can choose what you'd like.
We use GH Actions quite heavily with capa; our configuration is [here](https://github.com/mandiant/capa/tree/master/.github/workflows) if you'd like to review.
=> Add basic CI configuration

.github/workflows/lint.yml, setup.cfg, setup.py, src/dnfile/__init__.py, src/dnfile/base.py, src/dnfile/enums.py, src/dnfile/stream.py
(this depends on #4 for GH Actions configuration. please review and merge/reject that first).
This PR uses pycodestyle to identify potential code style issues. I've tuned the linter to suppress items that appear to conflict with the project's existing code style; still, you may not agree with how pycodestyle wants the code to look.
If you like this idea, its also configured for checking in GH Actions so violating code doesn't get merged.
If you don't like the idea: that's totally fine! No pressure to merge this PR. However, I think these style checkers can help preserve style when more contributors get involved (like @mike-hunhoff, @mmaps, and me) so I wanted to volunteer the effort to try one out.
Note: I'll open two more PRs like this that invoke the much-more-rigid checkers `black` and …
=> lint code with pycodestyle

src/dnfile/mdtable.py
seemed to be a missing property mapping
=> mdtable: implement TypeDefRow.Extends mapping

.github/workflows/lint.yml, examples/dnstrings.py, examples/typeref-list.py, setup.py, src/dnfile/__init__.py, src/dnfile/base.py, src/dnfile/codedindex.py, src/dnfile/enums.py, src/dnfile/mdtable.py, src/dnfile/stream.py, src/dnfile/utils.py
(this depends on #4 for GH Actions configuration. please review and merge/reject that first).
Like #6, this introduces a code linter that you can optionally decide to use for dnfile. If you like it, then this PR configures GH Actions to check for violations during CI. 
isort orders imports consistently. I've configured it here to do two things:
1. split imports by groups: stdlib, dependencies, project locals
2. order by line length
The idea here is to enforce a basic set of consistency. If you like it, please merge! If not, no worries!
Note: you can use the command `python -m isort --profile black --length-sort --line-width 120 .` to automatically apply all fixes recommended by isort. This is what I do with all my projects before pushing/creating a PR.
=> lint code with isort

src/dnfile/enums.py, src/dnfile/mdtable.py
closes #22
I haven't added any tests because I don't know how to cause these tables to be created. Parsing works against 0033ca037e0496c5c33e3dc19714fb3e now. 
I also don't know how to interpret the fields, so they're parsed as-is u32.
=> add parsing of EncLog and EncMap tables

examples/dndump.py
in obfuscated sample 0033ca037e0496c5c33e3dc19714fb3e, some strings, like a Module name, are invalid, and get rendered with escape sequences. this PR introduces a heuristic to identify "probably bad" strings and render them with a caveat.
from CFF explorer:
dndump (after PR):
=> dndump: better render invalid strings

src/dnfile/mdtable.py
closes #27 
adds parsing for:
- FieldPtr
- MethodPtr
- ParamPtr
CFF explorer doesn't parse these:
but I used the dnlib code to figure out how these should be interpreted.
unfortunately, the sample i have with these tables is private so i don't have any public tests i can add yet. here's dndump showing the parsed structures:
=> implement pointer rows

src/dnfile/stream.py, tests/test_invalid_strings.py
This PR add tests to demonstrate how to handle invalid UTF-16 strings from the `#US` heap. It relies on https://github.com/malwarefrank/dnfile-testfiles/pull/3 being merged and the submodule updated.
It also adds a routine to `UserStringHeap` to access the raw data used to form the string. This enables a user to fallback to the raw data if the string cannot be decoded as expected.
=> handling of invalid UTF-16 strings

setup.py
enables mypy to be able to recognized types already provided by this library. I used the reference here: https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages
=> add type annotation stuff for PEP 561 compatible packages

src/dnfile/enums.py, tests/test_parse.py
building on an idea from #20, use `setattr(..., False)` to provide the value `False` to unset flags and non-present enum variants. this means that the flag/enum properties are always present (and IDEs can autocomplete) and should be checked like:
```py
if cls.Flags.tdClass: ...
```
versus the old ways:
```
if hasattr(cls.Flags, "tdClass") and cls.Flags.tdClass: ...
if getattr(cls.Flags, "tdClass", False): ....
```
the new tests demonstrate this nicely:
i can think of no downsides, except the tiny performance overhead of setting more props on these instances.
=> comprehensively set flags and enums

tests/test_mixed_mode.py
relies on https://github.com/malwarefrank/dnfile-testfiles/pull/4 being merged and submodule updated here.
adds a couple test cases demonstrating the handling of mixed-mode assemblies. dnfile does perfectly, so this can serve as an example of how to interact with such programs.
=> add tests demonstrating handling of mixed-mode assemblies

src/dnfile/__init__.py, src/dnfile/base.py, src/dnfile/mdtable.py, src/dnfile/stream.py
Closes #20
Predictable attribute presence with default None or empty values:
- dnPE.net is None
- the follow dnPE.net attributes are set to None by default
- metadata
- strings
- user_strings
- guids
- blobs
- mdtables
- Flags
- MDTableRow objects - every attribute is initialized to None, except Lists which are initialized to empty
- MetadataTables stream object
- header is None
- tables is empty dict()
- tables_list is empty list()
- *_offset_size = 0
=> default values, remove duplicate warnings, and more inline comments

src/dnfile/base.py, tests/fixtures.py, tests/test_parse.py
fixes bug that introduced duplicate entries in table lists and updates `TypeDef` member tests to use a binary with sequential list runs.
=> fix off-by-one error w/ parsing table lists

src/dnfile/__init__.py, src/dnfile/base.py, src/dnfile/mdtable.py, src/dnfile/stream.py, src/dnfile/utils.py, tests/test_lazy_loading.py
Closes #73 
Some structure fields require all tables to be loaded in order to be fully initialized, so it may be a worth documenting these or allowing users to decide whether they're okay with these fields potentially being incomplete. 
ManifestRefRow.Implementation is one such field which is used when loading the assembly resources, so these are also parsed lazily.  
Timing loading the Celeste game executable to read the AssemblyReference names (my personal use-case) shows a very noticeable improvement with lazy loading enabled:
```
time.perf_counter: 4.960689430000002 (+- ~0.5)
#after
time.perf_counter: 0.01197438199960743 (+- ~0.003)
```
```py
import dnfile, time
pe = dnfile.dnPE("Celeste.exe", fast_load=True, clr_lazy_load=True)
start = time.perf_counter()
pe.parse_data_directories() …
```
=> Add optional lazy loading for .NET metadata tables

src/dnfile/resource.py
Note that `UnicodeDecodeError` is a subclass of `UnicodeError`, which is in turn a subclass of `ValueError`, so if `decode("utf-16")` fails it will throw `ValueError` before throwing `UnicodeDecodeError`.
=> Fix exception handling order in resource.py

src/dnfile/base.py, src/dnfile/stream.py, tests/test_invalid_streams.py, tests/test_invalid_strings.py, tests/test_parse.py
This adds support for easily identifying the RVA of any heap item, including Strings, Guids, and UserStrings.  It does so by creating HeapItem classes that contain the raw bytes, the decoded values, and the rva where the raw bytes were found in the underlying PE.
The .get() member of each of these heap streams now returns these objects. This is a potential **BREAKING CHANGE**, however the HeapItem subclasses can be treated similarly to what they represent.  The original .get() functions have been renamed to .get_bytes() or .get_str() where before they returned bytes or str.
HeapItemString and UserString can be indexed like and compared to strings.  HeapItemBinary can be indexed like and compared to bytes objects.
Closes #85
=> Heap streams return objects instead of raw bytes or strings

src/dnfile/resource.py
I've had several users encounter dotnet assemblies (mostly resource dlls) that cause dnfile to throw an `OverflowError: date value out of range` exception (stack trace below). Looking into the dotnet System.DateTime data type, the ticks value is actually just stored [using the lower 62-bits](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/DateTime.cs#L130-L138). The upper 2 bits are a DateTimeKind that is either unspecified, UTC, or Local.
Zeroing out the upper 2 bits resolves these cases for dotnet binaries with a "valid" System.DateTime (defined as up to 12/31/9999 23:59:59.9999999 according to a comment in the dotnet source code). However there is still a possibility that a malformed binary could encode a 62-bit value that still results in an …
=> Fix OverflowError when System.DateTime has DateTimeKind bits set

src/dnfile/__init__.py
Fixed typehint.
https://github.com/malwarefrank/dnfile/blob/b7dd509f56edb99b36c71e468bddbc92a8c5bcda/src/dnfile/__init__.py#L232-L233
https://github.com/malwarefrank/dnfile/blob/b7dd509f56edb99b36c71e468bddbc92a8c5bcda/src/dnfile/__init__.py#L311-L314
=> fix: typehint Version field in ClrMetaDataStruct as bytes
